build.gradle, src/main/java/com/jeju/nanaland/NanalandApplication.java, src/main/java/com/jeju/nanaland/domain/common/entity/BaseEntity.java, src/main/java/com/jeju/nanaland/domain/common/entity/Language.java
- BaseEntity 추가
- Language Entity 추가
<br>
<br>
close #1
=> [feat] 공통(Base), 언어(Language) Entity 추가

.gitignore, build.gradle, src/main/java/com/jeju/nanaland/global/ApiResponse.java, src/main/java/com/jeju/nanaland/global/exception/BadRequestException.java, src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/main/java/com/jeju/nanaland/global/exception/ServerErrorException.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java, src/main/java/com/jeju/nanaland/global/exception/UnauthorizedException.java
> 작업 내용
- ApiResponse 생성 (success, error 로구분)
- exception 생성
- ErrorCode, SuccesCode 생성
- ControllerAdvice 생성
- validation 의존성 추가
<br>
- succescode, errorcode, exception는 간단하게만 작성해두었습니다. 추후에 상황에 맞는 내용들만 추가하면 됩니다.
- postman 테스트를 위해 TestController ignore에 추가하였습니다.
<br>
> 관련 이슈
=> [Feat] ApiResponse, exception 추가

src/main/java/com/jeju/nanaland/global/exception/BadRequestException.java, src/main/java/com/jeju/nanaland/global/exception/UnauthorizedException.java
> 작업 내용
- exception 발생 시 메세지 입력 안하면 -> errorCode의 메세지로 응답 / 메세지 입력하면 -> 입력한 메세지로 응답
- 위의 로직 수정
<br>
<br>
> 관련 이슈
=> [#5] refactor: exception 에러 메세지 ErrorCode의 메세지 사용

build.gradle, src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/global/BaseResponse.java, src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java, src/main/java/com/jeju/nanaland/global/config/SwaggerConfig.java, src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java, src/main/java/com/jeju/nanaland/global/jwt/dto/JwtResponseDto.java, src/main/java/com/jeju/nanaland/global/jwt/handler/CustomAccessDeniedHandler.java, src/main/java/com/jeju/nanaland/global/jwt/handler/CustomAuthenticationEntryPoint.java
> 작업 내용
- swagger 의존성 추가
- swaggerConfig 추가
<br>
꼭 사용해야하는 어노테이션인지 잘 모르겠어서 일단 사용하지 않고 PR을 올립니다!~
ApiResponse -> BaseReponse로 수정하여 해결
-[] application.yml에 swagger 설정을 추가해주세용
```yaml
springdoc:
version: 1.0.0
default-consumes-media-type: application/json;charset=UTF-8
default-produces-media-type: application/json;charset=UTF-8
override-with-generic-response: false
writer-with-default-pretty-printer: true
swagger-ui:
disable-swagger-default-url: true
display-request-duration: true
tags-sorter: alpha
operations-sorter: method
groups-order: desc
```
<br>
> close #26
=> [Chore] Swagger 추가

src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
- swagger에서 파라미터 형식으로 보이도록 pageable 객체 제거
<br>
<br>
- close #34
=> [#34] refactor: search 컨트롤러 pageable 객체 제거

src/main/java/com/jeju/nanaland/global/imageUpload/S3ImageService.java
> 작업 내용
- 나나's pick 썸네일 이미지 직접 업로드를 위한 s3service 이미지 업로드 기능 분리
<br>
<br>
> 관련 이슈
=> [#16] refactor: s3 업로드 메서드 별도 구현

src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
- fix: searchService 충돌 해결
<br>
<br>
- close #38
=> [#38] fix: searchService 충돌 해결

src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java
- searchController 파라미터명 수정
-
<br>
<br>
- close #40
=> [#40] fix: searchController 파라미터명 수정

src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
- 500 error response 추가
<br>
<br>
- close #42
=> [#42] fix: 500 error response 추가

src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java
- 추천 게시물, 사용자 타입이 없을 때 에처러리
<br>
<br>
- close #44
=> [#44] fix: 추천 게시물, 사용자 타입이 없을 때 에처러리

appspec.yml, build.gradle, scripts/start.sh, scripts/stop.sh
=> [#47] feat: ci/cd 스크립트 작성

src/test/java/com/jeju/nanaland/domain/member/service/MemberTypeServiceTest.java
=> [#47] feat: ci/cd를 위한 테스틑 코드 주석 처리

src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java
=> [#22] feat: nanaDetail 조회 pathvariable id Long 타입으로 변경

src/main/java/com/jeju/nanaland/domain/common/entity/Common.java, src/main/java/com/jeju/nanaland/domain/experience/entity/Experience.java, src/main/java/com/jeju/nanaland/domain/festival/entity/Festival.java, src/main/java/com/jeju/nanaland/domain/hashtag/entity/Hashtag.java, src/main/java/com/jeju/nanaland/domain/market/entity/Market.java, src/main/java/com/jeju/nanaland/domain/nature/entity/Nature.java, src/main/java/com/jeju/nanaland/domain/nature/entity/NatureTrans.java
> 작업 내용
- common에 contentId 추가
- nature에 fee 추가
- festival에 startDate, endDate 추가
-  hashtag에 language 추가
<br>
> 관련 이슈
close #51
=> [#51] Feat: 필요한 필드 추가

src/main/java/com/jeju/nanaland/domain/common/entity/CommonTrans.java, src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceCompositeDto.java, src/main/java/com/jeju/nanaland/domain/experience/entity/ExperienceTrans.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/festival/dto/FestivalCompositeDto.java, src/main/java/com/jeju/nanaland/domain/festival/entity/FestivalTrans.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/market/dto/MarketCompositeDto.java, src/main/java/com/jeju/nanaland/domain/market/entity/MarketTrans.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nature/dto/NatureCompositeDto.java, src/main/java/com/jeju/nanaland/domain/nature/entity/NatureTrans.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java
> 작업 내용
- addressTag 추가
<br>
<br>
> 관련 이슈
=> [Feat] addressTag 추가

src/main/java/com/jeju/nanaland/domain/common/entity/Locale.java
=> [#71] feat: Locale에 베트남어 추가

src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
- 인기 검색어 최대 8개 반환
<br>
<br>
- close #70
=> [Refactor] 인기 검색어

src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java
- addressTagFilter에 아무것도 넣지 않았을 때 모두 조회
<br>
<br>
=> [#60] feat: 전통시장 조회, 상세조회

.github/workflows/gradle.yml, .github/workflows/test.yml
=> [#47] feat: workflow 수정

src/test/java/com/jeju/nanaland/domain/experience/service/ExperienceServiceTest.java, src/test/java/com/jeju/nanaland/domain/festival/service/FestivalServiceTest.java, src/test/java/com/jeju/nanaland/domain/market/service/MarketServiceTest.java, src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java, src/test/java/com/jeju/nanaland/domain/nature/service/NatureServiceTest.java
=> [#47] feat: test 코드 member -> memberInfoDto로 변경

src/test/java/com/jeju/nanaland/NanalandApplicationTests.java
=> [#47] feat: test 코드 test profile 적용

src/test/java/com/jeju/nanaland/NanalandApplicationTests.java
=> [#47] feat: @SpringBootTest 속성 삭제

build.gradle
=> [#47] feat: gradle test profile 적용

src/main/java/com/jeju/nanaland/domain/common/dto/CompositeDto.java, src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceCompositeDto.java, src/main/java/com/jeju/nanaland/domain/festival/dto/FestivalCompositeDto.java, src/main/java/com/jeju/nanaland/domain/market/controller/MarketController.java, src/main/java/com/jeju/nanaland/domain/market/dto/MarketCompositeDto.java, src/main/java/com/jeju/nanaland/domain/market/service/MarketService.java, src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java, src/main/java/com/jeju/nanaland/domain/nana/dto/NanaResponse.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java, src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java, src/main/java/com/jeju/nanaland/domain/nature/dto/NatureCompositeDto.java, src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java, src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java, src/main/java/com/jeju/nanaland/domain/search/dto/SearchResponse.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java, src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java
> 작업 내용
- 검색 후 상세 조회여서 RequestParam으로 isSearch가 true인 경우, redis에 key가 `searchVolume`이고 value는 `Category:id`로 값이 1씩 증가하도록 구현
- 이에 따라 가장 높은 4개의 게시물을 조회할 수 있도록 값을 가져옴
<br>
<br>
> 관련 이슈
close #93
=> [Feat] 검색량 측정, 검색량 up 게시물 조회

src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java, src/main/java/com/jeju/nanaland/domain/nana/dto/NanaResponse.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaTitleRepository.java, src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java
> 작업 내용
- response에 좋아요 표시 필드 추가
- nana 조회시 사용하던  id를 기존 nanaTitleId에서 nanaId로 일괄 변경
<br>
<br>
> 관련 이슈
=> [Feat] 나나 최종

src/main/java/com/jeju/nanaland/domain/nana/repository/NanaTitleRepository.java, src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
=> [#22] feat: nanaTitle 조회 시 Nana 이용하도록 수정

src/test/java/com/jeju/nanaland/domain/favorite/service/FavoriteServiceTest.java
=> [refactor] 찜리스트 테스트

src/main/java/com/jeju/nanaland/domain/festival/controller/FestivalController.java
=> [#61] feat: festival controller parameter 설명 수정

src/main/java/com/jeju/nanaland/domain/favorite/entity/Favorite.java, src/test/java/com/jeju/nanaland/domain/favorite/service/FavoriteServiceTest.java
- favorite 테이블 member_id, post_id, category_id 필드 유일 속성 추가
<br>
<br>
=> [Refactor] favorite 테이블 유일 속성 추가

src/main/java/com/jeju/nanaland/domain/nana/dto/NanaResponse.java, src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
> 작업 내용
- 나나스픽 상세 조회 시, version 추가
-
<br>
<br>
> 관련 이슈
close #127
=> [Feat] version 추가

src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
> 작업 내용
- Member 에 level 필드 추가
-
<br>
<br>
> 관련 이슈
=> [Feat] level 필드 추가

src/main/java/com/jeju/nanaland/domain/nana/dto/NanaResponse.java, src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
> 작업 내용
- 이모지 타입 response 추가
-
<br>
<br>
>  close #134
=> [#134] refactor: 이모지 구분을 위한 infoEmoji response에 추가

src/main/java/com/jeju/nanaland/domain/report/controller/ReportController.java
- merge develop 충돌 해결
<br>
<br>
=> [#94] feat: 정보 수정 요청

src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java
=> [#144] refactor: 테스트 코드 수정

src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
- 인기 검색어 수정
<br>
<br>
- close #152
=> [#152] fix : 인기 검색어 수정

src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
- 나나스픽 검색 범위 수정
- nanaTitle의 heading
- nanaContent의 title
- nanaContent의 content
- nanaContent의 해시태그 모두 포함
<br>
<br>
- close #154
=> [Feat] 나나스픽 검색 범위 수정

src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/entity/Member.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
> 작업 내용
- 로그인 시 language도 요청으로 받아올 수 있도록 함
- 따라서, 언어가 다른 경우 update될 수 있도록 함
<br>
<br>
> 관련 이슈
=> [Feat] 언어 변경 확인 후 업데이트

src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/entity/Member.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #161
=> [Feat] 이메일 unique 제거, 회원 가입 및 로그인 로직 중 이메일 관련 로직 제거

src/main/java/com/jeju/nanaland/domain/share/controller/ShareController.java, src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java, src/main/resources/templates/deeplink.html
- 딥링크 기능 구현
-
<br>
<br>
- close #166
=> [Feat] 딥링크

src/main/resources/templates/deeplink.html
- 딥링크 사진 추가, 지역 삭제
-
<br>
<br>
> 관련 이슈
=> [Feat] 딥링크 사진 추가, 지역 삭제

src/main/resources/templates/deeplink.html
- 딥링크 사진 추가
-
<br>
<br>
> 관련 이슈
=> [Feat] 딥링크 사진 추가

src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java
- 타입이 없는 사용자에 대한 추천
-
<br>
<br>
- close #177
=> [Fix] 타입이 없는 사용자에 대한 추천

src/main/resources/templates/deeplink.html
- deeplink 공유 이미지 설명 수정
-
<br>
<br>
> 관련 이슈
=> [Feat] deeplink 공유 이미지 설명 수정

src/main/java/com/jeju/nanaland/domain/share/controller/ShareController.java, src/main/resources/templates/deeplink-en.html, src/main/resources/templates/deeplink-ko.html, src/main/resources/templates/deeplink-ms.html, src/main/resources/templates/deeplink-zh.html
- 딥링크 언어별 설명
-
<br>
<br>
> 관련 이슈
=> [Feat] 딥링크 언어별 설명

src/main/java/com/jeju/nanaland/domain/nana/entity/Nana.java
=> [#191] refactor: nana의 nanaTitleImageFile unique 설정

src/main/java/com/jeju/nanaland/domain/common/annotation/EnumValid.java, src/main/java/com/jeju/nanaland/domain/common/annotation/EnumValidator.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
- 여행 타입 NONE으로 수정 불가
<br>
<br>
- close #182
=> [Feat] 여행 타입 NONE으로 수정 불가

src/main/java/com/jeju/nanaland/domain/hashtag/entity/Hashtag.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #190
=> [Feat] hashtag unique설정 추가

src/main/java/com/jeju/nanaland/domain/share/controller/ShareController.java, src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
=> [#184] feat: deeplink

src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/entity/MemberConsent.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
=> [Feat] 회원 정보 조회에 이용약관 추가

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberConsentService.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
> 작업 내용
- 이용약관 저장할 때의 방식을 변경(모든 이용약관에 대한 데이터가 생성되도록)
- 이용약관 수정 시, 불필요한 코드 삭제
<br>
<br>
> 관련 이슈
close #202
=> [Feat] 이용약관 생성 및 수정 로직 수정

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #206
=> [#206] feat: memberId가 아닌 토큰으로 변경

src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #209
=> [Fix] 본인의 닉네임과 중복되는 오류 해결

src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #214
=> [Feat] 7대 자연 리스트 조회에 keyword 추가

src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/entity/MemberConsent.java, src/main/java/com/jeju/nanaland/domain/member/entity/MemberTravelType.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberConsentService.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/test/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberConsentServiceTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
> 작업 내용
- memberLoginServiceTest
- memberConsentServiceTest
- memberRepositoryCustomTest
- memberProfileServiceTest
<br>
<br>
> 관련 이슈
close #181
=> [Test] member login test

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java
- 홈에서의 랜덤 추천 게시물 반환 API
<br>
<br>
- close #211
=> [Feat] 홈에서의 랜덤 추천 게시물 반환

src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java, src/test/java/com/jeju/nanaland/domain/search/service/SearchServiceTest.java
- member/type 기능 GUEST에 대해서도 허용
- HttpMethod.PATCH member/profile GUEST에 대해 권한 없음 처리
<br>
<br>
- close #219
=> [Feat] 게스트 기능 권한 수정

src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java, src/test/java/com/jeju/nanaland/domain/search/service/SearchServiceTest.java
=> [Feat] 게스트 기능 수정

src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
=> [#233] feat: 이메일이 없으면, 임시 지정

src/main/java/com/jeju/nanaland/domain/report/service/ReportService.java, src/main/resources/templates/deeplink-en.html, src/main/resources/templates/deeplink-ko.html, src/main/resources/templates/deeplink-ms.html, src/main/resources/templates/deeplink-zh.html
- 딥링크 URL 수정, 정보 수정 제안 이메일 수정
-
<br>
<br>
- close #239
=> [Feat] 딥링크 URL 수정, 정보 수정 제안 이메일 수정

src/main/java/com/jeju/nanaland/domain/nana/entity/InfoType.java, src/main/resources/templates/upload-nana.html
=> [#230] feat: NanaInfoType Call추가, upload html 수정

src/main/resources/templates/upload-nana.html
=> [#230] feat: 새로운 InfoType CALL html에 추가

src/main/java/com/jeju/nanaland/domain/nana/entity/InfoType.java, src/main/resources/templates/upload-nana.html
=> [Feat]: 새로운 InfoType CALL html에 추가

src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryImpl.java, src/main/resources/templates/upload-nana.html
- 타입 테스트 결과 이미지 origin으로 변경
<br>
<br>
> 관련 이슈
=> [Feat] 타입 테스트 결과 이미지 origin으로 변경

build.gradle, src/main/java/com/jeju/nanaland/domain/favorite/controller/FavoriteController.java, src/main/java/com/jeju/nanaland/domain/favorite/dto/FavoriteResponse.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepository.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java, src/main/java/com/jeju/nanaland/domain/festival/service/FestivalService.java, src/main/java/com/jeju/nanaland/domain/market/service/MarketService.java, src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java, src/test/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/favorite/service/FavoriteServiceTest.java, src/test/java/com/jeju/nanaland/domain/market/service/MarketServiceTest.java
- mvp2의 favorite 기능
<br>
<br>
- close #256
=> [Feat] mvp2 favorite

src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java
=> [#269] hotfix: s3ImageService 썸네일 높이 aspectRatio 0일 경우 450 반환

src/test/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImplTest.java
=> [#269] hotfix: findNanaThumbnailPostDto Test 주석처리

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/entity/Recommend.java, src/main/java/com/jeju/nanaland/domain/member/entity/RecommendTrans.java, src/main/java/com/jeju/nanaland/domain/member/entity/enums/TravelType.java, src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java, src/main/resources/templates/deeplink-en.html, src/main/resources/templates/deeplink-ko.html, src/main/resources/templates/deeplink-ms.html, src/main/resources/templates/deeplink-zh.html, src/test/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberTypeServiceTest.java
- TravelType 클래스에서 중국어, 말레이어 컨셉 이름 수정
- 추천 결과에 대한 이미지를 따로 보여줄 수 있도록 변경
- 안드로이드 딥링크 경로 수정
<br>
- recommend 테이블에서 ImageFile 테이블과 다대일 연관관계 추가
<br>
- close #273
=> [hotfix] 타입 추천 기능 수정

scripts/execute-deploy.sh
- nginx 무중단 배포 설정
- 액츄에이터 설정으로 현재 서버의 버전 정보 확인 가능
<br>
<br>
=> [Hotfix] nginx 설정

src/main/java/com/jeju/nanaland/domain/version/controller/VersionController.java, src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
- aos version 반환 API
- ios version 반환 API
<br>
<br>
- close #287
=> [Hotfix] version API

.github/workflows/push_pr_to_develop.yml
=> [#282] refactor: githubactions workflow 이름 수정

src/main/java/com/jeju/nanaland/domain/review/dto/ReviewResponse.java, src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java, src/test/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImplTest.java, src/test/java/com/jeju/nanaland/domain/review/service/ReviewServiceTest.java
> 작업 내용
- 다시보니, 작성자의 리뷰 평균이 아니였고 정작 필요한 리뷰 점수를 빠트린 상황인지라 새로 반영해주었습니다.
-
<br>
<br>
> 관련 이슈
close #300
=> [Test] review list 테스트 코드

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/entity/Member.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
> 작업 내용
- `/member/profile`에서 `/member/profile?id=`로 변경
- id가 null인 경우엔 내 프로필로 조회
- id가 회원의 id와 일치하는 경우도 내 프로필로 조회
- 다른 경우, 상대 회원 프로필로 조회
<br>
<br>
> 관련 이슈
close #302
=> [Feat] 유저 프로필 조회 수정

src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java
> 작업 내용
- 401에러로 반환되는 것을 방지하고자 Exception 추가
-
<br>
<br>
> 관련 이슈
close #242
=> [Refactor] 500 error

src/main/java/com/jeju/nanaland/domain/review/controller/ReviewController.java, src/main/java/com/jeju/nanaland/domain/review/dto/ReviewResponse.java, src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/review/service/ReviewService.java, src/test/java/com/jeju/nanaland/domain/review/service/ReviewServiceTest.java
> 작업 내용
- 회원 별 작성한 리뷰 리스트 조회 API
- 회원 프로필과 마찬가지로 memberId가 없으면 본인의 리뷰 리스트 조회, 그렇지 않으면 다른사람의 리뷰 리스트 조회
- 회원 별 작성한 리뷰 미리보기 리스트 조회 API (12개만)
<br>
<br>
> 관련 이슈
close #305
=> [Feat] 회원별 리뷰 리스트 조회

src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
=> [Feat] 회원 프로필 사진 ImageFileDto 반환

src/main/java/com/jeju/nanaland/domain/experience/entity/ExperienceTrans.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #315
=> [Feat] 이색체험 varchar 적용

src/main/java/com/jeju/nanaland/domain/notice/controller/NoticeController.java, src/main/java/com/jeju/nanaland/domain/notice/dto/NoticeResponse.java, src/main/java/com/jeju/nanaland/domain/notice/entity/Notice.java, src/main/java/com/jeju/nanaland/domain/notice/entity/NoticeCategory.java, src/main/java/com/jeju/nanaland/domain/notice/entity/NoticeContent.java, src/main/java/com/jeju/nanaland/domain/notice/entity/NoticeTitle.java, src/main/java/com/jeju/nanaland/domain/notice/repository/NoticeRepository.java, src/main/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/notice/service/NoticeService.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java, src/test/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryImplTest.java, src/test/java/com/jeju/nanaland/domain/notice/service/NoticeServiceTest.java
> 작업 내용
- 공지사항 리스트 조회 API
- 공지사항 상제 조회 API
<br>
- `image - content`를 하나의 세트로 구성하여서 진행하였습니다.
<br>
> 관련 이슈
close #313
=> [Feat] 공지사항 리스트 조회, 상세 조회 

src/main/java/com/jeju/nanaland/domain/common/entity/VideoFile.java, src/main/java/com/jeju/nanaland/domain/common/repository/VideoFileRepository.java, src/main/java/com/jeju/nanaland/domain/common/service/VideoFileService.java, src/main/java/com/jeju/nanaland/domain/report/controller/ReportController.java, src/main/java/com/jeju/nanaland/domain/report/dto/ReportRequest.java, src/main/java/com/jeju/nanaland/domain/report/entity/review/ClaimType.java, src/main/java/com/jeju/nanaland/domain/report/entity/review/ReviewReport.java, src/main/java/com/jeju/nanaland/domain/report/entity/review/ReviewReportImageFile.java, src/main/java/com/jeju/nanaland/domain/report/entity/review/ReviewReportVideoFile.java, src/main/java/com/jeju/nanaland/domain/report/repository/ReviewReportImageFileRepository.java, src/main/java/com/jeju/nanaland/domain/report/repository/ReviewReportRepository.java, src/main/java/com/jeju/nanaland/domain/report/repository/ReviewReportVideoFileRepository.java, src/main/java/com/jeju/nanaland/domain/report/service/ReportService.java, src/main/java/com/jeju/nanaland/domain/review/entity/claim/ClaimType.java, src/main/java/com/jeju/nanaland/domain/review/entity/claim/ReviewClaim.java, src/main/java/com/jeju/nanaland/domain/review/entity/claim/ReviewClaimImageFile.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java, src/main/java/com/jeju/nanaland/global/image_upload/S3VideoService.java, src/main/java/com/jeju/nanaland/global/image_upload/dto/S3VideoDto.java, src/main/resources/templates/info-fix-report.html, src/main/resources/templates/review-report.html, src/test/java/com/jeju/nanaland/domain/report/service/ReportServiceTest.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #320
=> [Feat] 리뷰 신고 API 구현

src/main/java/com/jeju/nanaland/domain/common/service/ImageFileService.java, src/main/java/com/jeju/nanaland/domain/report/controller/ReportController.java, src/main/java/com/jeju/nanaland/domain/report/dto/ReportRequest.java, src/main/java/com/jeju/nanaland/domain/report/entity/InfoFixReport.java, src/main/java/com/jeju/nanaland/domain/report/entity/InfoFixReportImageFile.java, src/main/java/com/jeju/nanaland/domain/report/repository/InfoFixReportImageFileRepository.java, src/main/java/com/jeju/nanaland/domain/report/service/ReportService.java, src/main/resources/templates/info-fix-report.html, src/test/java/com/jeju/nanaland/domain/report/service/ReportServiceTest.java
- 정보 수정 제안 다중 이미지
<br>
- 아직 개발중이어서 nanaland 메일이 아닌 제 개인 이메일로 요청이 오도록 바꿔뒀습니다. 실제 배포할때는 다시 바꿔놓도록 하겠습니다.
<br>
- close #312
=> [Feat] 정보 수정 제안 다중 이미지처리

src/main/java/com/jeju/nanaland/domain/experience/entity/enums/ExperienceTypeKeyword.java, src/main/java/com/jeju/nanaland/domain/restaurant/dto/RestaurantCompositeDto.java, src/main/java/com/jeju/nanaland/domain/restaurant/dto/RestaurantResponse.java, src/main/java/com/jeju/nanaland/domain/restaurant/entity/RestaurantTrans.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/restaurant/service/RestaurantService.java
- 기존 RestaurantTrans 필드 수정
- reservation, takeOut, parking, groupReservation, pet -> service 로 통합
- ExperienceTypeKeyword 수정
- 농총체험 -> 농촌체험 으로 수정
<br>
<br>
- close #326
=> [Refactor] 맛집 상세조회 service 정보 추가

src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java, src/main/java/com/jeju/nanaland/domain/search/dto/SearchResponse.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
- 맛집 검색 기능 추가
<br>
- #326 RestaurantTrans 테이블을 수정한 브랜치와 merge 한 이후에 이 브랜치에 push 했습니다.
<br>
- close #321
=> [Feat] 맛집 검색 추가

src/main/java/com/jeju/nanaland/domain/review/entity/ReviewImageFile.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #330
=> [Fix] reviewImageFile에 BaseEntity 삭제

src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java
=> [Fix] fetchReviewImages에서 limit 삭제

src/main/java/com/jeju/nanaland/domain/review/controller/ReviewController.java
=> [#306] feat: 자동완성 post -> get 수정

src/main/java/com/jeju/nanaland/domain/favorite/controller/FavoriteController.java, src/main/java/com/jeju/nanaland/domain/favorite/dto/FavoriteRequest.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java
- 맛집 찜리스트 조회 추가
-
<br>
<br>
- close #336
=> [Feat] 맛집 찜리스트 조회

src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceResponse.java, src/main/java/com/jeju/nanaland/domain/experience/service/ExperienceService.java
- 이색체험 상세조회 intro 추가
-
<br>
<br>
- close #340
=> [Refactor] 이색체험 상세조회 intro 추가

src/main/java/com/jeju/nanaland/domain/restaurant/entity/RestaurantMenu.java
- restaurant_menu의 first_image_file_id -> image_file_id 로 변경
-
<br>
<br>
- close #344
=> [Refactor] 메뉴 이미지 파일 매핑 컬럼명 변경

src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java
- 리뷰 상세조회 쿼리 수정
<br>
<br>
- close #350
=> [Hotfix] 리뷰 상세조회 수정

src/main/java/com/jeju/nanaland/domain/common/entity/Post.java
- post 연관관계 ManyToOne 으로 수정
-
<br>
<br>
- close #353
=> [Refactor] post 연관관계 수정

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #357
=> [Feat] 닉네임 중복 확인 API

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #357
=> [Feat] memberId 유무에 따른 닉네임 중복 검사, profileDto에 memberId 추가

.gitignore, src/main/java/com/jeju/nanaland/domain/member/entity/RecommendTrans.java, src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepository.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java
- recommend_trans introduction -> varchar(1024)로 수정
- 랜덤 추천 게시물 반환 기능 수정
<br>
<br>
- close #365
=> [Feat] 추천 게시물 조회

src/main/java/com/jeju/nanaland/domain/nana/dto/NanaResponse.java, src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
=> [#367] refactor: 나나스픽 게시물 new 태그 가장 최신 게시물에 작성

src/main/java/com/jeju/nanaland/domain/notification/config/FirebaseConfig.java, src/main/java/com/jeju/nanaland/domain/notification/entity/NanalandNotification.java
- 알림 기능 firebase config 수정
<br>
<br>
=> [Feat] firebase config 수정

src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java
- 좋아요 기능 fix
<br>
<br>
- close #380
=> [Hotfix] 좋아요 기능 fix

src/main/java/com/jeju/nanaland/domain/notice/entity/NoticeCategory.java, src/main/java/com/jeju/nanaland/domain/review/entity/ReviewTypeKeyword.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #377
=> [Refactor] 공지사항, 리뷰타입 번역 추가

src/main/java/com/jeju/nanaland/domain/admin/controller/AdminController.java, src/main/java/com/jeju/nanaland/domain/admin/controller/AdminNotificationController.java, src/main/java/com/jeju/nanaland/domain/admin/service/AdminLoginService.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/domain/notification/controller/NotificationController.java, src/main/java/com/jeju/nanaland/domain/notification/data/NotificationRequest.java, src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java, src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java, src/main/java/com/jeju/nanaland/global/exception/ForbiddenException.java, src/main/resources/templates/admin/admin-home.html, src/main/resources/templates/admin/admin-login.html, src/main/resources/templates/admin/admin-notification-to-all.html, src/main/resources/templates/admin/admin-notification-to-target.html
- admin page 작성
- 알림 전체 전송, 개별 전송 지원
<br>
- 
<br>
- close #383
=> [Feat] 알림 admin page

src/main/java/com/jeju/nanaland/domain/admin/controller/AdminController.java, src/main/java/com/jeju/nanaland/domain/admin/controller/AdminNotificationController.java
=> [Feat] 관리자 페이지

src/main/java/com/jeju/nanaland/domain/common/service/PostServiceImpl.java
- postService refactoring
-
<br>
<br>
> 관련 이슈
=> [Refactor] postService refactoring

src/main/resources/templates/admin/admin-notification-to-target.html
- 개별알림 전송 관리자페이지 html 수정
-
<br>
<br>
- #401
=> [Hotfix] 관리자페이지 수정

src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java, src/test/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImplTest.java
=> [#409] hotfix: heading, subheading 정렬 수정

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/entity/MemberWithdrawal.java, src/main/java/com/jeju/nanaland/domain/member/entity/enums/TravelType.java, src/main/java/com/jeju/nanaland/domain/member/entity/enums/WithdrawalType.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberConsentService.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java, src/main/java/com/jeju/nanaland/domain/notification/service/FcmTokenService.java, src/main/java/com/jeju/nanaland/global/auth/AuthMemberArgumentResolver.java, src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java, src/main/java/com/jeju/nanaland/global/util/JwtUtil.java, src/test/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberConsentServiceTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
> 작업 내용
- 변수명, 함수명 규칙에 맞추어 수정
<br>
<br>
> 관련 이슈
close #390
=> [Refactor] member 리팩토링

src/main/java/com/jeju/nanaland/domain/notice/controller/NoticeController.java, src/main/java/com/jeju/nanaland/domain/notice/dto/NoticeResponse.java, src/main/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/notice/service/NoticeService.java, src/test/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryImplTest.java, src/test/java/com/jeju/nanaland/domain/notice/service/NoticeServiceTest.java
> 작업 내용
- 공지사항과 관련된 부분의 DTO명, 함수명 리팩토링 진행
<br>
<br>
> 관련 이슈
close #392
=> [Refactor] 공지사항(notice) 리팩토링

src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #412
=> [Fix] 닉네임 유효 확인 API permitAll 적용

src/main/java/com/jeju/nanaland/domain/review/dto/ReviewResponse.java, src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #414
=> [Feat] 리뷰 좋아요 여부 추가

src/main/java/com/jeju/nanaland/domain/version/controller/VersionController.java
- 버전 정보 API 추가
-
<br>
<br>
- close #418
=> [Feat] version info api

src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
=> [#418] feat: version info

src/main/java/com/jeju/nanaland/domain/member/entity/RecommendTrans.java, src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryImpl.java, src/test/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryTest.java
- 추천게시물 `별자리 여행` 과 같이 게시물 제목과 다를 경우에 대한 처리, 테스트코드
<br>
<br>
- close #424
=> [Hotfix] 추천게시물 별도 제목 추가

src/main/java/com/jeju/nanaland/domain/nana/dto/NanaResponse.java
=> [#403] refactor: 변경된 Dto 명, name 속성 부여

src/main/java/com/jeju/nanaland/domain/nana/entity/InfoType.java
=> [#437] hotfix: additional info에 sns 추가

src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/entity/enums/TravelType.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
- /member/profile api에 travelTypeKey 필드 추가
-
<br>
<br>
- close #439
=> [#439] hotfix: 프로필 조회 필드 수정

src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
=> [Fix] 유저 프로필 조회 시 언어 설정 수정

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
=> [Fix] 정규식 수정

src/main/java/com/jeju/nanaland/domain/share/controller/ShareController.java, src/main/resources/templates/deeplink-vi.html
- 베트남어 딥링크 추가
-
<br>
<br>
- close #445
=> [#445] hotfix/#445-deeplink

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
#447
=> [Fix] 닉네임 정규식 수정

src/main/java/com/jeju/nanaland/domain/common/data/AddressTag.java, src/main/java/com/jeju/nanaland/domain/experience/controller/ExperienceController.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/experience/service/ExperienceService.java, src/main/java/com/jeju/nanaland/domain/festival/controller/FestivalController.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/festival/service/FestivalService.java, src/main/java/com/jeju/nanaland/domain/market/controller/MarketController.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/market/service/MarketService.java, src/main/java/com/jeju/nanaland/domain/nana/entity/InfoType.java, src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java, src/main/java/com/jeju/nanaland/domain/restaurant/controller/RestaurantController.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/restaurant/service/RestaurantService.java, src/test/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/market/service/MarketServiceTest.java, src/test/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryTest.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #450
=> [Refactor] address filter Enum으로 수정

src/main/java/com/jeju/nanaland/domain/notification/service/FavoriteNotificationService.java, src/main/java/com/jeju/nanaland/domain/notification/service/NotificationService.java
=> [#454] hotfix: 좋아요 알림 수정

src/main/java/com/jeju/nanaland/domain/notification/repository/NanalandNotificationRepositoryImpl.java
=> [#454] hotfix: 알림 조회 쿼리 수정

src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
=> [Feat] cors 설정 추가

src/main/java/com/jeju/nanaland/global/config/SwaggerConfig.java
=> [Docs] swagger URL 설정 수정

src/main/java/com/jeju/nanaland/domain/restaurant/entity/RestaurantTrans.java
- restaurant_trans, service 컬럼 VARCHAR(1024)로 수정
-
<br>
<br>
- close #474
=> [#474] refactor: restaurant_trans, service 컬럼 수정

src/main/java/com/jeju/nanaland/domain/common/service/ImageFileService.java, src/main/java/com/jeju/nanaland/domain/common/service/MailService.java, src/main/java/com/jeju/nanaland/domain/common/service/VideoFileService.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java, src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java, src/main/java/com/jeju/nanaland/global/image_upload/S3VideoService.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #476
=> [Refactor] 에러메시지 수정

src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
- securityConfig /actuator/health 허용하도록 수정
-
<br>
<br>
- close #484
=> [#484] fix: securityConfig 수정

src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
- 스웨거 접속 권한 변경
-
<br>
<br>
- close #487
=> [#487] fix: 스웨거 접속 권한 변경

src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/domain/notification/entity/FcmToken.java
- fcmToken 테이블 member_id, token 컬럼 Unique 처리
-
<br>
<br>
- close #489
=> [Fix] fcmToken 중복 금지 처리

src/main/java/com/jeju/nanaland/global/config/SwaggerConfig.java
> 작업 내용
-
-
<br>
<br>
- close #492
=> [#492] fix: swaggerConfig 변경

src/main/java/com/jeju/nanaland/global/config/RedisConfig.java
=> [Feat] RedisConfig에 Database 추가

src/main/java/com/jeju/nanaland/domain/common/entity/ImageFile.java, src/main/java/com/jeju/nanaland/domain/common/service/ImageFileService.java, src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java, src/main/java/com/jeju/nanaland/domain/member/service/ProfileImageService.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
> 작업 내용
- 프로필 삭제 기능 추가
-
<br>
<br>
> 관련 이슈
close #463
=> [Feat] 프로필 삭제

src/main/java/com/jeju/nanaland/global/config/S3Config.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java, src/main/java/com/jeju/nanaland/global/file/controller/FileUploadController.java, src/main/java/com/jeju/nanaland/global/file/data/FileCategory.java, src/main/java/com/jeju/nanaland/global/file/dto/FileRequest.java, src/main/java/com/jeju/nanaland/global/file/dto/FileResponse.java, src/main/java/com/jeju/nanaland/global/file/service/FileUploadService.java, src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java
> 작업 내용
- PreSigned URL로 업로드하겠다고 요청하는 /upload-init 구현
- PreSigned URL로 업로드 한 후 완료 요청하는 /upload-complete 구현
<br>
- Postman으로 실행해보니 S3에는 잘 올라갑니다.
- 아직 MultipartFile로 받아와 저장해왔었던 API에서 코드 수정을 하지 않았습니다. (회원 프로필 설정, 리뷰, 신고 등)
- 비동기로 사진 저장하는 부분과 S3ImageService 코드는 아마 앞으로 사용되지 않을 것 같아 삭제가 될 것 같아보입니다 (multipartFile을 받아오지 않기 때문)
- AWS Lambda로 이미지 포맷 변환과 리사이징 적용을 고려하고 있습니다. (위 작업을 모두 마치면 시도해보려구요)
<br>
> 관련 이슈
=> [Feat] presigned URL 추가

src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/global/auth/AuthMemberArgumentResolver.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #509
=> [Feat] 에러 메시지 수정

src/main/java/com/jeju/nanaland/domain/member/entity/Member.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #511
=> [Fix] 회원 탈퇴 시, providerId 수정

src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
=> [#511] feat: swagger requestMachers에 추가

src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java
- 홈 추천게시물 3개 반환
-
<br>
<br>
- close #503
=> [Fix] 홈 추천게시물 3개 반환

src/main/java/com/jeju/nanaland/domain/common/dto/PopularPostPreviewDto.java, src/main/java/com/jeju/nanaland/domain/common/service/PostViewCountService.java
=> [#519] refactor: 인기 게시물 찜 여부 추가

src/main/java/com/jeju/nanaland/domain/common/dto/SearchDto.java, src/main/java/com/jeju/nanaland/domain/nana/dto/NanaSearchDto.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java
- 나나스픽 중복 검색 결과 문제 수정
-
<br>
<br>
> 관련 이슈
=> [Fix] 나나스픽 검색 수정

src/main/java/com/jeju/nanaland/domain/common/service/ImageFileService.java, src/main/java/com/jeju/nanaland/domain/review/controller/ReviewController.java, src/main/java/com/jeju/nanaland/domain/review/dto/ReviewRequest.java, src/main/java/com/jeju/nanaland/domain/review/entity/ReviewImageFile.java, src/main/java/com/jeju/nanaland/domain/review/service/ReviewService.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/main/java/com/jeju/nanaland/global/file/data/ImageSize.java, src/main/java/com/jeju/nanaland/global/file/service/FileUploadService.java
=> [Feat] review 이미지 처리 수정

src/main/java/com/jeju/nanaland/domain/review/dto/ReviewResponse.java, src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java, src/test/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImplTest.java, src/test/java/com/jeju/nanaland/domain/review/service/ReviewServiceTest.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #531
=> [Feat] 이색체험 세부 카테고리로 응답되도록 수정

src/main/java/com/jeju/nanaland/domain/favorite/controller/FavoriteController.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java
- 이색체험 찜리스트 액티비티와 문화예술로 구분
-
<br>
<br>
- close #534
=> [#534] fix: 이색체험 찜리스트 수정

src/main/java/com/jeju/nanaland/domain/nana/entity/InfoType.java
=> [#541] refactor: 나나스픽 infoType website 말레이어 수정

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberTypeServiceTest.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
close #546
=> [Feat] 다른 사용자 추천 여행지 조회 기능 추가

src/main/java/com/jeju/nanaland/domain/common/dto/PopularPostPreviewDto.java, src/main/java/com/jeju/nanaland/domain/common/service/PostViewCountService.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
=> [#545] refactor: 지난주 인기 게시물 experience 카테고리 세분화

src/main/java/com/jeju/nanaland/domain/notification/service/FavoriteNotificationService.java
- 찜 알림 전송 얼어별로 변경
-
<br>
<br>
- close #550
=> [hotfix] 언어별 푸시알림

src/main/java/com/jeju/nanaland/domain/address/controller/AddressController.java, src/main/java/com/jeju/nanaland/domain/address/service/AddressService.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java, src/test/java/com/jeju/nanaland/domain/address/service/AddressServiceTest.java, src/test/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryTest.java
- 한국어 주소 제공 API
-
<br>
<br>
- close #553
=> [Feat] 한국어 주소 제공 API

src/main/java/com/jeju/nanaland/domain/restaurant/service/RestaurantService.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
> 작업 내용
- 검색량 up 이색체험 카테고리를 문화예술, 액티비티로 분리
-
<br>
<br>
> 관련 이슈
close #555
=> [Fix] 검색량 up 게시물 이색체험 카테고리 분리

src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java, src/test/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryTest.java
- 검색 필터적용
-
<br>
<br>
- close #556
=> [#556] feat: 검색 필터 적용

src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java
=> [Fix] 맛집검색 필터 오류 수정

src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java, src/test/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryTest.java
- 이색체험 검색 필터 오류 수정
-
<br>
<br>
=> [Fix] 이색체험 검색 필터 오류 수정

src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
- 이색체험 검색결과 카테고리 구분
-
<br>
<br>
- close #561
=> [hotfix] 이색체험 검색결과 카테고리 구분
