build.gradle, src/main/java/com/jeju/nanaland/NanalandApplication.java, src/main/java/com/jeju/nanaland/domain/common/config/QuerydslConfig.java, src/main/java/com/jeju/nanaland/domain/common/entity/BaseEntity.java, src/main/java/com/jeju/nanaland/domain/common/entity/Common.java, src/main/java/com/jeju/nanaland/domain/common/entity/CommonTrans.java, src/main/java/com/jeju/nanaland/domain/common/entity/Language.java, src/main/java/com/jeju/nanaland/domain/experience/entity/Experience.java, src/main/java/com/jeju/nanaland/domain/experience/entity/ExperienceTrans.java, src/main/java/com/jeju/nanaland/domain/festival/entity/Festival.java, src/main/java/com/jeju/nanaland/domain/festival/entity/FestivalTrans.java, src/main/java/com/jeju/nanaland/domain/market/entity/Market.java, src/main/java/com/jeju/nanaland/domain/market/entity/MarketTrans.java, src/main/java/com/jeju/nanaland/domain/nana/entity/Nana.java, src/main/java/com/jeju/nanaland/domain/nana/entity/NanaTrans.java, src/main/java/com/jeju/nanaland/domain/nature/entity/Nature.java, src/main/java/com/jeju/nanaland/domain/nature/entity/NatureTrans.java, src/main/java/com/jeju/nanaland/domain/stay/entity/Stay.java, src/main/java/com/jeju/nanaland/domain/stay/entity/StayTrans.java
- common > entity 에 BaseEntity를 상속받는 Common, CommonTrans 엔티티 추가
- Nana, NanaTrans 엔티티 추가
- 6대 카테고리 엔티티 추가
- querydsl 의존성 추가
- DB의존성 추가 (main - mariadb, test - H2)
- common > config 에 QuerydslConfig 설정 파일 추가
<br>
<br>
stay는 common을 상속받고 stayTrans는 baseEntity를 상속받는데 괜찮을까요?
=> [Feat] Common, 6대 카테고리 엔티티 추가, querydsl 의존성 추가, DB의존성 추가

src/main/java/com/jeju/nanaland/domain/common/entity/Common.java, src/main/java/com/jeju/nanaland/domain/common/entity/CommonTrans.java, src/main/java/com/jeju/nanaland/domain/experience/entity/Experience.java, src/main/java/com/jeju/nanaland/domain/experience/entity/ExperienceTrans.java, src/main/java/com/jeju/nanaland/domain/festival/entity/Festival.java, src/main/java/com/jeju/nanaland/domain/festival/entity/FestivalTrans.java, src/main/java/com/jeju/nanaland/domain/market/entity/Market.java, src/main/java/com/jeju/nanaland/domain/market/entity/MarketTrans.java, src/main/java/com/jeju/nanaland/domain/nana/entity/Nana.java, src/main/java/com/jeju/nanaland/domain/nana/entity/NanaTrans.java, src/main/java/com/jeju/nanaland/domain/nature/entity/Nature.java, src/main/java/com/jeju/nanaland/domain/nature/entity/NatureTrans.java, src/main/java/com/jeju/nanaland/domain/stay/entity/Stay.java, src/main/java/com/jeju/nanaland/domain/stay/entity/StayTrans.java, src/test/java/com/jeju/nanaland/domain/entity/EntityBuilderTest.java
- @NoArgsConstructor에 `access = AccessLevel.PROTECTED` 추가
- @JoinColumn에 `name, nullable` 추가
- `@Column(columnDefinition = "TEXT")`로 데이터 타입 변경
- `CommonTrans`의 content, address
- `NanaTrans`의 content
- `@Column(columnDefinition = "VARCHAR(2048)")`로 데이터 타입 변경
- `CommonTrans`의 address
- `StayTrans`의 address
- `Nana`의 imageUrl
- `Common`의 imageUrl
- `Festival`의 homepage
- `Market`의 homepage
- `Stay`의 homepage
- 매핑관계 `orphanRemoval = true` 삭제
- 빌더패턴 테스트코드
<br>
<br>
=> [Feat] 엔티티 형식 통일, 긴 문자열 데이터 타입 변경, 빌더 테스트코드

src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java, src/main/java/com/jeju/nanaland/global/config/WebConfig.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/main/java/com/jeju/nanaland/global/jwt/AuthMember.java, src/main/java/com/jeju/nanaland/global/jwt/AuthMemberArgumentResolver.java, src/main/java/com/jeju/nanaland/global/jwt/JWTAuthenticationFilter.java, src/main/java/com/jeju/nanaland/global/jwt/JwtProvider.java, src/main/java/com/jeju/nanaland/global/jwt/JwtUtil.java
> 작업 내용
- `Jwtprovider.getAuthentication()`에서 `UserDetailService.loadUserByUsername()`을 호출하는 부분을 삭제했습니다.
- 이 부분을 삭제하고 진행을 하기 위해선 Jwt에 authorities를 포함해야 했기에 Jwt 생성 함수도 일부 수정되었습니다.
- `@AuthMember`라는 커스텀 어노테이션을 생성하였습니다.
<br>
1. environment 생성
2. 맨 우측화면에서 environment 설정
3. `/member/login` TEST 탭에 코드 추가
```javascript
if(pm.response.code === 200) {
var jsonData = pm.response.json();
var accessToken = jsonData.data.accessToken;
var refreshToken = jsonData.data.refreshToken;
pm.environment.set('token', accessToken);
pm.environment.set('refreshToken', refreshToken);
}
```
4. 다른 API에서 변수 설정해주기
이상입니다!!!
<br>
> close #27
=> [Feat] Jwt 생성 및 검증 부분 수정, 커스텀 어노테이션 추가

src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
- 언어 별로 인기 검색어 8개 조회
<br>
- 인기 검색어에 여러 언어가 있는게 부자연스럽다고 생각해서 우선 ranking_KOREAN, ranking_ENGLISH 등으로 key를 설정해서 언어별로 인기 검색어를 반환하게 구현했습니다.
- 시간 별로 인기 검색어를 어떻게 보여줘야 하나 고민하다가 우선 다음과 같은 방법으로 구현했습니다. 
<br>
- close #30
=> [#30] feat: 인기 검색어 조회

src/main/java/com/jeju/nanaland/domain/common/annotation/EnumValidator.java, src/main/java/com/jeju/nanaland/domain/common/entity/Locale.java, src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/entity/Provider.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepository.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/global/exception/ConflictException.java, src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
> 작업 내용
- 이미 존재하는 회원인지 예외 처리 (기존에는 DB에 도달해야 확인할 수 있었던 상황,,)
- Enum valid 추가
- 임시로 랜덤 프로필 사진을 추가하는 함수를 간단하게 수정해두었습니다.
<br>
아,,, 이슈 번호를 커밋 메시지 앞에 붙이는 것을 까먹어버렸습니다.. 이미 push를 했던 지라 수정하려면 강제로 force로 push해야하는데 이건 좀 안될 것 같아 시도하지 않았습니다. 다음엔 꼭 잊지않고 번호 붙이겠습니다ㅠㅠ
<br>
> 관련 이슈
close #33
=> [Feat] 로그인 회원 생성 로직 수정

src/main/java/com/jeju/nanaland/domain/common/data/CategoryContent.java, src/main/java/com/jeju/nanaland/domain/common/entity/Category.java, src/main/java/com/jeju/nanaland/domain/common/repository/CategoryRepository.java, src/main/java/com/jeju/nanaland/domain/experience/controller/ExperienceController.java, src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceRequest.java, src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceResponse.java, src/main/java/com/jeju/nanaland/domain/experience/service/ExperienceService.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepository.java, src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java, src/main/java/com/jeju/nanaland/domain/festival/controller/FestivalController.java, src/main/java/com/jeju/nanaland/domain/festival/service/FestivalService.java, src/main/java/com/jeju/nanaland/domain/market/controller/MarketController.java, src/main/java/com/jeju/nanaland/domain/market/service/MarketService.java, src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java, src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java, src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java, src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java, src/test/java/com/jeju/nanaland/domain/entity/EntityImageFileMappingTest.java, src/test/java/com/jeju/nanaland/domain/experience/service/ExperienceServiceTest.java, src/test/java/com/jeju/nanaland/domain/festival/service/FestivalServiceTest.java, src/test/java/com/jeju/nanaland/domain/market/service/MarketServiceTest.java, src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java, src/test/java/com/jeju/nanaland/domain/nature/service/NatureServiceTest.java
- 게시물 좋아요, 좋아요 취소 토글 기능 구현
- 해당 게시물에 대해 좋아요 상태라면 좋아요 취소, 좋아요 상태가 아니라면 좋아요 상태로 변경
- test 코드
- 좋아요 2번 실행, 1번 실행 결과 테스트
- 없는 게시물의 id로 요청 시 BadRequestException 반환 테스트
<br>
- Category의 String content 필드 -> Enum 타입 CategoryContent로 변경
<br>
- close #54
=> [#54] Feat : 게시물 좋아요, 좋아요 취소

.gitignore, src/main/java/com/jeju/nanaland/domain/experience/controller/ExperienceController.java, src/main/java/com/jeju/nanaland/domain/festival/controller/FestivalController.java, src/main/java/com/jeju/nanaland/domain/market/controller/MarketController.java, src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepository.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java, src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java, src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java, src/main/java/com/jeju/nanaland/global/jwt/AuthMemberArgumentResolver.java
> 작업 내용
- `@AuthMember`에서 언어도 조회해오도록 수정
<br>
<br>
> 관련 이슈
=> [Refactor] `@AuthMember` 수정

src/main/java/com/jeju/nanaland/domain/festival/dto/FestivalCompositeDto.java, src/main/java/com/jeju/nanaland/domain/festival/entity/Festival.java, src/main/java/com/jeju/nanaland/domain/festival/entity/Season.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nana/entity/NanaContent.java
> 작업 내용
- Festival에 season 필드 추가
<br>
nanaContent에서 nana_contet_id를 nana_content_id로 오타를 수정하였습니다. 해당 pr이 반영되고 난 후에는 db에 새로 nana_content_id가  생기게 되지만, nana_contet_id는 사라지지 않을 거 같습니다.
또한, addressTag 종류 중에 "우도"가 추가되어서,, 이를 따로 update하는 코드를 짜기보단 통합해버리는 게 나을 거 같다고도 생각이 들었습니다.
season과 addressTag를 통합한 파이썬 코드를 노션에 올려두었으니, 데이터베이스를 drop하고 새로 create하는 것이 깔끔할 것 같다라는 생각이 들어서 통합된 파이썬 코드를 올리게 되었습니다.
<br>
> 관련 이슈
=> [Feat] season 추가

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
> 작업 내용
- swagger 문서에서 refreshToken 재발행 api에서 Authorization에 토큰을 담는 입력 칸이 동작하지 않음
- swagger config를 통해 설정해준 swagger 문서 내의 Authroize 기능을 통해 refreshToken을 담아 요청하면 잘 동작하기 때문에,  해당 입력칸이 보여지지 않도록 hidden 처리함
<br>
<br>
> 관련 이슈
=> [Docs] refreshToken hidden 처리

src/main/java/com/jeju/nanaland/domain/favorite/controller/FavoriteController.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java, src/main/java/com/jeju/nanaland/domain/festival/entity/FestivalTrans.java, src/test/java/com/jeju/nanaland/domain/favorite/service/FavoriteServiceTest.java
- FavoriteRepositoryImpl 각 쿼리에서 category 비교 where문 추가
- FavoriteRepositoryImpl 의 `find{ ... }ThumbnailByPostId` 에서 해당 카테고리의 id와 favorite의 postId 가 동일한지 체크
- 좋이요 요청 토글 {id} pathvariable 삭제
- FavoriteService테스트 코드 작성
<br>
- FestivalTrans 의 fee 필드 ` @Column(columnDefinition = "VARCHAR(1024)")` 추가
- nana 테이블의 id를 Favorite의 postId로 사용하도록 통일
<br>
- close #101
=>  [Refactor] 찜리스트

src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java, src/main/java/com/jeju/nanaland/domain/search/dto/SearchResponse.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java, src/test/java/com/jeju/nanaland/config/TestConfig.java, src/test/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/favorite/service/FavoriteServiceTest.java, src/test/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/search/service/SearchServiceTest.java
- NANA를 제외한 카테고리 검색 범위 수정
- 제목에 포함
- 본문에 포함
- 위치태그와 일치
- 공백을 기준으로 분리했을때 해당 해시태그들이 게시물의 해시태그 리스트에 모두 포함될때
<br>
- 아직 NANA쪽 기능 구현이 덜 된것 같아서, 해당 기능 구현 완료되면 NANA 검색도 수정하겠습니다.
- searchController에서 모든 카테고리 조회를 favorite과 통일성 있게 하기 위해서 엔드포인트를 search/all로 바꿨습니다.
<br>
- close #99
=> [Refactor] 검색 범위 수정

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/entity/MemberWithdrawal.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/member/repository/MemberWithdrawalRepository.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
> 작업 내용
-
-
<br>
-> admin만 가능한 api로 만들까도 하였으나, 프론트 개발자분들이 회원 탈퇴 api 후에 강제 회원 탈퇴 api를 실행해야 하다보니, 여기에 admin으로 로그인까지 해야하면 번거로워하실 것 같아서 그냥 permitall해두었습니다.
운영하기 전엔 꼭 admin으로 바꾸던지 api를 삭제해야 할 것 같네용
<br>
> 관련 이슈
close #206
=> [Feat] 비회원 이용약관 로직 수정 & 회원 탈퇴 조회 로직 수정 & 강제 회원 탈퇴 API

src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryImpl.java
- 타입 추천 결과창에서 추천 이미지 화질이 깨져서 origin 이미지로 반환
<br>
- 지금 반환 필드는 thumbnail 인데 이걸 origin으로 변경하면 프론트 분들도 변동사항이 생겨서 놔뒀습니다.
- 예전에 얘기한대로 MVP2에서는 origin이랑 thumbnail을 모두 반환하고 프론트에서 원하는 걸 가져다 쓰는 방식으로 하면 좋을 거 같아요
<br>
- close #244
=> [Refactor] 추천 이미지 origin 이미지로 반환

src/main/java/com/jeju/nanaland/domain/restaurant/entity/Restaurant.java, src/main/java/com/jeju/nanaland/domain/restaurant/entity/RestaurantMenu.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java
- restaurant 엔티티 contentId 추가
- restaurantMenu, imageFIle 연관관계 ManyToOne으로 변경
- 메뉴 조회시 없는 이미지 처리를 위해 left join으로 변경
<br>
- 다른 post를 상속받는 엔티티와의 통일성, 그리고 맛집 데이터를 넣을 때, DB상의 id로 데이터를 넣는것보다 임의로 contentId를 정해서 넣어주는게 더 유지보수할 때 좋을 거 같아서 추가했습니다.
- RestaurantMenu 엔티티에서, 서로 다른 튜플(같은 메뉴 다른 언어)이 같은 imageFile 을 참조할 수 있도록 ManyToOne 연관관계로 설정했습니다.
<br>
- close #338
=> [Feat] 맛집 엔티티 변경

src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java
- 맛집, 이색체험 count 쿼리 수정
<br>
- 리스트 조회 시 필터링 부분에서 keyword 조건 때문에 join을 했을 때, 키워드가 여러 개인 경우 실제 자료보다 count 쿼리의 수가 더 많아지는 부분이 있었습니다. 따라서 countDistinct를 사용했습니다.
<br>
- close #348
=> [Refactor] 맛집, 이색체험 count 쿼리 수정

src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java, src/test/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/favorite/service/FavoriteServiceTest.java
- 찜리스트 정렬 기준을 createdAt에서 modifiedAt으로 변경
<br>
- 좋아요 알림을 중복해서 보내지 않기 위해서 favorite을 ACTIVE, INACTIVE 상태로 관리합니다.
- 찜을 취소했다가 다시 눌렀을 경우 가장 첫번째로 보여져야 하지만, 기존 방법대로 created_at을 기준으로 정렬하면 값이 바뀌지 않아서 modified_at을 기준으로 정렬하도록 바꿨습니다.
<br>
> 관련 이슈
=> [Hotfix] 찜리스트 정렬기준 변경

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
> 작업 내용
- 닉네임이 중복되지 않았는데, 중복되었다는 응답이 왔다는 소식에 일단 살펴보았는데, 제 로컬에서는 해당 오류가 재현되지가 않더라구요. 일단 닉네임 중복 로직에서 불필요한 부분을 제거하고 정규식을 추가하는 작업을 하여 수정했습니다.
<br>
<br>
> 관련 이슈
close #447
=> [Fix] 유저 닉네임 중복 로직 수정

src/main/java/com/jeju/nanaland/domain/common/service/FileService.java, src/main/java/com/jeju/nanaland/global/config/AsyncConfig.java, src/main/java/com/jeju/nanaland/global/util/CustomMultipartFile.java
=> [Fix] 이미지 비동기 설정 수정

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java, src/main/java/com/jeju/nanaland/domain/member/service/ProfileImageService.java, src/main/java/com/jeju/nanaland/global/config/S3Config.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java, src/main/java/com/jeju/nanaland/global/file/controller/FileUploadController.java, src/main/java/com/jeju/nanaland/global/file/data/FileCategory.java, src/main/java/com/jeju/nanaland/global/file/dto/FileRequest.java, src/main/java/com/jeju/nanaland/global/file/dto/FileResponse.java, src/main/java/com/jeju/nanaland/global/file/service/FileUploadService.java, src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
> 작업 내용
- preSigned URL을 적용함으로써, MultipartFile을 해당 API에서 받아오지 않기 때문에 제거합니다.
- 또한, 기존에는 S3에서의 URL을 그대로 가지고 왔다면, CloudFront가 적용된 url로 가지고 옵니다.
- 기본 프로필의 경우, 이미 이미지 사이즈가 크지 않기 때문에, originUrl와 thumbnailUrl은 동일하게 가져가려고 합니다.
- 또한, s3에 default라는 폴더를 따로 만들어서 개발용, 운영용 가리지 않고 모두 `default/Gray.png`의 형태로 고정됩니다.
<br>
<br>
> 관련 이슈
close #505
close #463
related to #495
=> [Feat] 회원 프로필 수정 API에서 MultipartFile 제거

src/main/java/com/jeju/nanaland/domain/review/dto/ReviewRequest.java, src/main/java/com/jeju/nanaland/domain/review/entity/ReviewTypeKeyword.java, src/main/java/com/jeju/nanaland/domain/review/service/ReviewService.java
> 작업 내용
- 리뷰 키워드 필수 개수 1개로 수정
- "선택할 키워드가 없어요"에 해당하는 NONE 키워드 추가
- NONE 키워드의 경우 따로 저장할 필요성을 느끼지 못하여, NONE인 경우에는 저장하지 않도록 로직 추가
<br>
<br>
> 관련 이슈
close #453
=> [Feat] 리뷰 키워드 필수 개수 수정 및 키워드 추가

src/main/java/com/jeju/nanaland/domain/common/dto/SearchDto.java, src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceSearchDto.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/festival/dto/FestivalSearchDto.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/market/dto/MarketSearchDto.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nana/dto/NanaSearchDto.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/nature/dto/NatureSearchDto.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/restaurant/dto/RestaurantSearchDto.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java, src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java, src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java, src/test/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryTest.java, src/test/java/com/jeju/nanaland/domain/search/service/SearchServiceTest.java
- 제목, 내용, 지역필터, 키워드 중 키워드를 포함하는 게시물 검색
- 공백으로 구분된 검색어가 4개 이하라면, 위 조건 중 하나라도 포함하면 검색 결과에 포함. 많이 겹친 순, 최신 순으로 결과 반환
- 검색어가 5개 이상이라면 모든 키워드가 겹치는 게시물만을 반환
<br>
- 
<br>
- close #521
=> [Fix] 검색 조건 수정

src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java, src/test/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImplTest.java
- 나나스픽 검색 결과 중복 문제 수정
-
<br>
<br>
- close #524
=> [Fix] 나나스픽 검색 수정

src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java, src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java, src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java, src/main/java/com/jeju/nanaland/global/file/dto/FileRequest.java, src/main/java/com/jeju/nanaland/global/file/service/FileUploadService.java, src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java
> 작업 내용
-
-
<br>
<br>
> 관련 이슈
related to #495
=> [feat] 회원 가입 수정
